import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import ConvexClientProvider from "@/providers/convex-client-provider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
           <ConvexClientProvider>
           {children}
           <Toaster />
           </ConvexClientProvider>
         </ThemeProvider>
      </body>
    </html>
  );
}


// import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
// import './globals.css';

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     // <ClerkProvider>
//     <ConvexClientProvider>
//       <html lang="en">
//         <body>
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="system"
//           enableSystem
//           disableTransitionOnChange
//         >
//           {/* <ConvexClientProvider> */}
//             <main>
//            {children}
//            </main>
//           <Toaster />
//            {/* </ConvexClientProvider> */}
//          </ThemeProvider>
//           <header>
//             <SignedOut>
//               <SignInButton />
//             </SignedOut>
//             <SignedIn>
//               <UserButton />
//             </SignedIn>
//           </header>
//           {/* <main>
//             {children}
//           </main> */}
//         </body>
//       </html>
//     {/* // </ClerkProvider> */}
//     </ConvexClientProvider>
//   )
// }